version: 0.2
env:
  exported-variables:
    - IMAGE_REPO_NAME
    - IMAGE_TAG
phases:
  install:
    runtime-versions:
      dotnet: 3.1
      docker: 19
  pre_build:
    commands:
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7) 
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_NBR.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker Image...
      - echo Tagging and pushing the Docker image...
      - dotnet publish -c Release -r linux-x64
      - OutputDirectory=`echo /bin/Release/net5.0/linux-x64/publish`
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .

      # push to ecr with latest tag
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_NBR.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_NBR.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      # - docker images

      # push to ecr with git hash
      - docker push $AWS_ACCOUNT_NBR.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest
      - docker push $AWS_ACCOUNT_NBR.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
